const Fiat = [
    { asset_id: "PLN", name: "Zloty", type_is_crypto: 0 },
    { asset_id: "EUR", name: "Euro", type_is_crypto: 0 },
    { asset_id: "CNY", name: "Yuan Renminbi", type_is_crypto: 0 },
    { asset_id: "JPY", name: "Yen", type_is_crypto: 0 },
    { asset_id: "AUD", name: "Australian Dollar", type_is_crypto: 0 },
    { asset_id: "CHF", name: "Swiss Franc", type_is_crypto: 0 },
    { asset_id: "SEK", name: "Swedish Krona", type_is_crypto: 0 },
    { asset_id: "GBP", name: "Pound Sterling", type_is_crypto: 0 },
    { asset_id: "DKK", name: "Danish Krone", type_is_crypto: 0 },
    { asset_id: "RUB", name: "Russian Ruble", type_is_crypto: 0 },
    { asset_id: "SGD", name: "Singapore Dollar", type_is_crypto: 0 },
    { asset_id: "CAD", name: "Canadian Dollar", type_is_crypto: 0 },
    { asset_id: "NZD", name: "New Zealand Dollar", type_is_crypto: 0 },
    { asset_id: "THB", name: "Baht", type_is_crypto: 0 },
    { asset_id: "KRW", name: "Won", type_is_crypto: 0 },
    { asset_id: "SVC", name: "El Salvador Colon", type_is_crypto: 0 },
    { asset_id: "BRL", name: "Brazilian Real", type_is_crypto: 0 },
    { asset_id: "CLP", name: "Chilean Peso", type_is_crypto: 0 },
    { asset_id: "TOP", name: "TopCoin", type_is_crypto: 0 },
    { asset_id: "BOB", name: "Boliviano", type_is_crypto: 0 },
    { asset_id: "CHC", name: "WIR Franc (for electronic)", type_is_crypto: 0 },
    { asset_id: "VND", name: "Dong", type_is_crypto: 0 },
    { asset_id: "MYR", name: "Malaysian Ringgit", type_is_crypto: 0 },
    { asset_id: "CRC", name: "Costa Rican Colon", type_is_crypto: 0 },
    { asset_id: "NLG", name: "Netherlands Guilder", type_is_crypto: 0 },
    { asset_id: "XAU", name: "Gold", type_is_crypto: 0 },
    { asset_id: "MAD", name: "Moroccan Dirham", type_is_crypto: 0 },
    { asset_id: "ESP", name: "Spanish Peseta", type_is_crypto: 0 },
    { asset_id: "PEN", name: "Nuevo Sol", type_is_crypto: 0 },
    { asset_id: "GHS", name: "Ghana Cedi", type_is_crypto: 0 },
    { asset_id: "CZK", name: "Czech Koruna", type_is_crypto: 0 },
    { asset_id: "HKD", name: "Hong Kong Dollar", type_is_crypto: 0 },
    { asset_id: "BRE", name: "Cruzeiro", type_is_crypto: 0 },
    { asset_id: "UAH", name: "Hryvnia", type_is_crypto: 0 },
    { asset_id: "MVR", name: "Rufiyaa", type_is_crypto: 0 },
    { asset_id: "TRY", name: "Turkish Lira", type_is_crypto: 0 },
    { asset_id: "INR", name: "Indian Rupee", type_is_crypto: 0 },
    { asset_id: "MXN", name: "Mexican Peso", type_is_crypto: 0 },
    { asset_id: "BRC", name: "Cruzado", type_is_crypto: 0 },
    { asset_id: "PHP", name: "Philippine Peso", type_is_crypto: 0 },
    { asset_id: "IDR", name: "Rupiah", type_is_crypto: 0 },
    { asset_id: "ARS", name: "Argentine Peso", type_is_crypto: 0 },
    { asset_id: "NGN", name: "Naira", type_is_crypto: 0 },
    { asset_id: "ZAR", name: "Rand", type_is_crypto: 0 },
    { asset_id: "AED", name: "United Arab Emirates Dirham", type_is_crypto: 0 },
    { asset_id: "RON", name: "New Romanian Leu", type_is_crypto: 0 },
    { asset_id: "XPT", name: "Platinum", type_is_crypto: 0 },
    { asset_id: "NOK", name: "Norwegian Krone", type_is_crypto: 0 },
    { asset_id: "ILS", name: "New Israeli Sheqel", type_is_crypto: 0 },
    { asset_id: "HUF", name: "Forint", type_is_crypto: 0 },
    { asset_id: "BGN", name: "Bulgarian Lev", type_is_crypto: 0 },
    { asset_id: "HRK", name: "Croatian Kuna", type_is_crypto: 0 },
    { asset_id: "LTT", name: "Talonas", type_is_crypto: 0 },
    { asset_id: "BHD", name: "Bahraini Dinar", type_is_crypto: 0 },
    { asset_id: "AOA", name: "Angolan Kwanza", type_is_crypto: 0 },
    { asset_id: "SCR", name: "Seychelles Rupee", type_is_crypto: 0 },
    { asset_id: "CHE", name: "WIR Euro", type_is_crypto: 0 },
    { asset_id: "SSP", name: "South Sudanese Pound", type_is_crypto: 0 },
    { asset_id: "MTL", name: "Maltese Lira", type_is_crypto: 0 },
    { asset_id: "BHT", name: "BHT", type_is_crypto: 0 },
    { asset_id: "COP", name: "Colombian Peso", type_is_crypto: 0 },
    {
      asset_id: "XBC",
      name: "Bond Markets Unit of Account 9",
      type_is_crypto: 0
    },
    { asset_id: "AMD", name: "Armenian Dram", type_is_crypto: 0 },
    { asset_id: "ADP", name: "Andorran Peseta", type_is_crypto: 0 },
    { asset_id: "ISK", name: "Iceland Krona", type_is_crypto: 0 },
    { asset_id: "UYU", name: "Peso Uruguayo", type_is_crypto: 0 },
    { asset_id: "PYG", name: "Guarani", type_is_crypto: 0 },
    { asset_id: "KGS", name: "Som", type_is_crypto: 0 },
    { asset_id: "YUN", name: "Yugoslavian Dinar", type_is_crypto: 0 },
    { asset_id: "HRD", name: "Croatian Dinar", type_is_crypto: 0 },
    { asset_id: "MTP", name: "Maltese Pound", type_is_crypto: 0 },
    { asset_id: "BTCMZ", name: "BTCMZ", type_is_crypto: 0 },
    { asset_id: "KZT", name: "Tenge", type_is_crypto: 0 },
    { asset_id: "ANG", name: "Netherlands Antillean Guilder", type_is_crypto: 0 },
    { asset_id: "SAR", name: "Saudi Riyal", type_is_crypto: 0 },
    { asset_id: "BGL", name: "Lev", type_is_crypto: 0 },
    { asset_id: "AWG", name: "Aruban Florin", type_is_crypto: 0 },
    { asset_id: "BEL", name: "Financial Franc", type_is_crypto: 0 },
    { asset_id: "STD", name: "Dobra", type_is_crypto: 0 },
    { asset_id: "PTE", name: "Portuguese Escudo", type_is_crypto: 0 }
  ];
  
  export default Fiat;
  